version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./pgbackup:/backup
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: DMD2user
      POSTGRES_PASSWORD: DMD2pgPass
      POSTGRES_DB: dvdrental

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ${HOME}/neo4j/data:/data
      - ${HOME}/neo4j/logs:/logs
      - ${HOME}/neo4j/import:/import
      - ${HOME}/neo4j/plugins:/plugins
      - ${HOME}/neo4j/backup:/backup
    environment:
      - NEO4J_AUTH=neo4j/bitnami
volumes:
  db-data:
