version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
      - ./pgbackup:/backup
      - export:/tmp
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: DMD2user
      POSTGRES_PASSWORD: DMD2pgPass
      POSTGRES_DB: dvdrental

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/logs:/var/lib/neo4j/logs
      - export:/var/lib/neo4j/import
      - ./neo4j/plugins:/var/lib/neo4j/plugins
    environment:
      - NEO4J_AUTH=neo4j/bitnami
volumes:
  db-data:
  export:
